### PR TITLE
Responsive Compatible

### PR DESCRIPTION
**Pull request by alexarn**

### CODE REVIEW

**Comment by alexarn** [comment]
Branch rebased on master

**Review by alexarn — COMMENTED** [review]
Adding new working hours (/workinghour/add): agent input pass under the start input (ok on branch master)
On the framework index page (/framework) the button "supprimer la sélection" pass over the frameworks table.
In all the datatable, buttons for copy, Excel etc... get out the white background.
In absence and holiday index, buttons ("rechercher", "réinitialiser" and "ajouter") are not aligned with the left form elements.
Globaly, in all the page, there is a bigger space at the top of the page between the content (page title) and the main menu.
Also, in the menu, the links are shifted to the right and the "My account" link pass at the right of account name.

**Comment by jeromecombes** [comment]
Branch rebased on master

**Comment by jeromecombes** [comment]
Replaced with #886 and #887

**Pull request closed without merging**
