### PR TITLE
symfonize attendance hours

### PR DESCRIPTION
**Pull request by sillydebs**

### CODE REVIEW

**Comment by alexarn** [comment]
File templates/workinghour/edit.html.twig should not be in this pull request.

After saving working hours for an agent, i'm redirected to index.php?page=planningHebdo//workinghour&msg=Le+planning+a+été+ajouté+avec+succès.&msgType=success
  => access denied

If i click on "retour", i'm redirected to index.php?page=planningHebdo/
  => access denied

**Review by alexarn — CHANGES_REQUESTED** [review]
File templates/workinghour/edit.html.twig should not be in this pull request.

After saving working hours for an agent, i'm redirected to index.php?page=planningHebdo//workinghour&msg=Le+planning+a+été+ajouté+avec+succès.&msgType=success
=> access denied

If i click on "retour", i'm redirected to index.php?page=planningHebdo/
=> access denied

**Comment by sillydebs** [comment]
> File templates/workinghour/edit.html.twig should not be in this pull request.
> 
> After saving working hours for an agent, i'm redirected to index.php?page=planningHebdo//workinghour&msg=Le+planning+a+été+ajouté+avec+succès.&msgType=success
> => access denied
> 
> If i click on "retour", i'm redirected to index.php?page=planningHebdo/
> => access denied

Thank you for your review, I corrected my code following your report.

**Comment by didier-g** [comment]
Hi,

Works for me.

Regards
Didier

**Review by didier-g — APPROVED** [review]
Work for me

**Review by alexarn — APPROVED** [review]

**Comment by alexarn** [comment]
Merged on master. Thx Sarah !

**Pull request closed without merging**
