### PR TITLE
Symfonize compensatory time

### PR DESCRIPTION
**Pull request by alexarn**

### CODE REVIEW

**Review by jeromecombes — CHANGES_REQUESTED** [review]
Tests with APP_DEBUG=1 return access denied when changing the year with dropdown menu : 
Bug 1 : 
<pre>
Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: config" at /var/www/html/plb/src/Controller/CompTimeController.php line 174</pre>
--> Fix it by using $this->config('Conges-Recuperations') 

Bug 2 : 
<pre> Uncaught PHP Exception Twig\Error\RuntimeError: "Key "hourstodays" for array with keys "id, date, date2, name, hours, validation_style, validation, validation_date, credits, commentaires" does not exist." at /var/www/html/plb/templates/comp_time/index.html.twig line 243 </pre>

**Comment by jeromecombes** [comment]
> Tests with APP_DEBUG=1 return access denied when changing the year with dropdown menu :
> Bug 1 :
> 
> Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: config" at /var/www/html/plb/src/Controller/CompTimeController.php line 174
> 
> --> Fix it by using $this->config('Conges-Recuperations')
> 
> Bug 2 :
> 
>  Uncaught PHP Exception Twig\Error\RuntimeError: "Key "hourstodays" for array with keys "id, date, date2, name, hours, validation_style, validation, validation_date, credits, commentaires" does not exist." at /var/www/html/plb/templates/comp_time/index.html.twig line 243



Fix : $comptime['hourstodays'] initialization

<pre>
--- a/src/Controller/CompTimeController.php
+++ b/src/Controller/CompTimeController.php
@@ -171,7 +171,8 @@ class CompTimeController extends BaseController
                 'commentaires'      => html_entity_decode($elem['commentaires'], ENT_QUOTES|ENT_HTML5),
             );
 
-            if ($config['Conges-Recuperations'] == 0 && $holiday_helper->showHoursToDays()) {
+            $comptime['hourstodays'] = null;
+            if ($this->config('Conges-Recuperations') == 0 && $holiday_helper->showHoursToDays()) {
                 $comptime['hourstodays'] = $holiday_helper->hoursToDays($elem['heures'], $elem['perso_id']);
             }
</pre>

**Review by jeromecombes — COMMENTED** [review]
I was able to register a comp-time for an agent who is not in a managed site by clicking on "Nouvelle demande".
(There is probably the same error on master and 20.10.xx)

@alexarn can you see if we can use the "get_agents" function from HollidayController ?
It can be done in another PR.

**Comment by jeromecombes** [comment]
> > Tests with APP_DEBUG=1 return access denied when changing the year with dropdown menu :
> > Bug 1 :
> > Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: config" at /var/www/html/plb/src/Controller/CompTimeController.php line 174
> > --> Fix it by using $this->config('Conges-Recuperations')
> > Bug 2 :
> > Uncaught PHP Exception Twig\Error\RuntimeError: "Key "hourstodays" for array with keys "id, date, date2, name, hours, validation_style, validation, validation_date, credits, commentaires" does not exist." at /var/www/html/plb/templates/comp_time/index.html.twig line 243
> 
> Fix : $comptime['hourstodays'] initialization
> 
> --- a/src/Controller/CompTimeController.php
> +++ b/src/Controller/CompTimeController.php
> @@ -171,7 +171,8 @@ class CompTimeController extends BaseController
>                  'commentaires'      => html_entity_decode($elem['commentaires'], ENT_QUOTES|ENT_HTML5),
>              );
>  
> -            if ($config['Conges-Recuperations'] == 0 && $holiday_helper->showHoursToDays()) {
> +            $comptime['hourstodays'] = null;
> +            if ($this->config('Conges-Recuperations') == 0 && $holiday_helper->showHoursToDays()) {
>                  $comptime['hourstodays'] = $holiday_helper->hoursToDays($elem['heures'], $elem['perso_id']);
>              }

Fixed with e1a922c8a8501ade97e1f03b4e7c76a1b7374320

**Comment by jeromecombes** [comment]
> I was able to register a comp-time for an agent who is not in a managed site by clicking on "Nouvelle demande".
> (There is probably the same error on master and 20.10.xx)
> 
> @alexarn can you see if we can use the "get_agents" function from HollidayController ?
> It can be done in another PR.

Confirmed : same thing on master
We are going to fix it in another PR

**Review by jeromecombes — APPROVED** [review]

**Comment by alexarn** [comment]
merged on master

**Pull request closed without merging**
